__title__ = "Japanera"
__description__ = "Easy japanese era tool"
__url__ = "https://github.com/delta114514/Japanera"
__version_info__ = ("0", "0", "3")
__version__ = ".".join(__version_info__)
__author__ = "Yamato Nagata"
__author_email__ = "chickenwingswillfly@gmail.com"
__maintainer__ = "Yamato Nagata"
__license__ = "MIT"
__copyright__ = "(c) 2019 by Yamato Nagata"
